
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root123@
    url: jdbc:mysql://localhost:3306/stream_spring
    username: root
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  servlet:
    multipart:
      max-file-size: 2GB
      max-request-size: 2GB
server:
  servlet:
    context-path: /stream_spring